services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  auth-service:
    build: ./services/auth-service
    ports: ["8081:8081"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB:-appdb}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-app}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-app}
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    depends_on: [db]

  social-service:
    build: ./services/social-service
    ports: ["8082:8082"]

  email-service:
    build: ./services/email-service
    ports: ["8083:8083"]

  crm-service:
    build: ./services/crm-service
    ports: ["8084:8084"]

  gateway-service:
    build: ./services/gateway-service
    ports: ["8080:8080"]
    depends_on: [auth-service, social-service, email-service, crm-service]

  ui:
    build: ./ui
    ports: ["5173:5173"]
    environment: [ "VITE_API_BASE=http://localhost:8080" ]
    depends_on: [gateway-service]

volumes:
  pgdata:
